version: '3.9'
services:
  peer2profit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peer2profit
    image: enwaiax/peer2profit:latest
    restart: unless-stopped
    environment:
      - email=chasing0806@gmail.com
      - use_proxy=false
    volumes:
      - ./proxychains4.conf:/root/proxychains4.conf
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging: 
      driver: "local"
      options:
        max-size: "1m"